### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by emile135** [alfredapp/switch-appearance-workflow#2]
### Workflow version

v2024.1

### Alfred version

5.5

### macOS version

Sonoma 14.5

### Debugger output

```alfred_debugger
[22:06:02.414] Logging Started...
[22:06:08.591] Switch Appearance[Keyword] Processing complete
[22:06:08.600] Switch Appearance[Keyword] Passing output '' to Automation Task
[22:06:08.603] Switch Appearance[Automation Task] Running task 'Set Dark Mode' with no arguments
[22:06:08.915] ERROR: Switch Appearance[Automation Task] Task Error (1): /Users/emile/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/Automation Tasks/75497895812253bc98feecf4b447d1f9783ebd2d6b101fe118186ee025ee2234: execution error: Error: Error: An error occurred. (-1743)
```

### More details

When i use the keyword 'light' to set Light mode nothing actually happens

**Comment by vitorgalvao** [comment]
Start by rebooting your Mac. If that doesn’t fix it, make sure your [Automation Tasks are up to date](https://www.alfredapp.com/help/workflows/automations/automation-task/#update).

**Comment by emile135** [comment]
Thanks for the reply. I already restarted my mac a few times and also updated the automation tasks but still nothing happens

**Comment by vitorgalvao** [comment]
Try switching appearance in the System Settings a couple of times to "reset it" then try the workflow again.

**Comment by emile135** [comment]
I tried it but unfortunately that doesn't seem to fix the problem

**Comment by vitorgalvao** [comment]
Open [Script Editor](https://support.apple.com/en-gb/guide/script-editor/scpedt1079/mac) and change the language to JavaScript. Then run the following code. What is the result?

```javascript
var appearance = Application("System Events").appearancePreferences
appearance.darkMode = !appearance.darkMode()
```

**Comment by emile135** [comment]
Yes, this does toggle the dark mode

**Comment by vitorgalvao** [comment]
Make sure Alfred can automate System Events, under System Setting → Privacy & Security → Automation. If the toggle is already on:

1. Quit Alfred.
2. Turn the toggle off.
3. Turn the toggle on.
4. Open Alfred.

**Comment by emile135** [comment]
YES! you found it, apparently alfred had never asked me about this so it was not turned on yet. Thanks a lot for the help man

**Comment by vitorgalvao** [comment]
Really took digging deep for this one! Glad you’re sorted.

For reference, those options should only even appear when macOS asks for that permission, so something toggled off should indicate it was either refused when asked (could’ve been a misclick) or that it was turned off afterwards. *In theory*, because in practice we know permissions on macOS sometimes bug out for any app, so could’ve been anything.

Have a nice weekend!
